# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        IMAG\LdapBundle\User\LdapUser: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        ldap:
            id: imag_ldap.security.user.provider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            provider: ldap
            imag_ldap: ~
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /requests
                #csrf_provider: security.csrf.token_manager
            logout:
                #success_handler: security.logout.handler
                path:   /logout
                target: /login  
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_LDAP }
imag_ldap:
    client:
        host: ldap://ldap.nyumc.org
        port: 389
        version: 3
        username: NYUMC\webappadmin
        password: w3bappadm1n
#    network_timeout: 10 # Optional
        referrals_enabled: false
#    bind_username_before: false # Optional
#    skip_roles: false # Optional
    user:
        base_dn: dc=nyumc,dc=org
        filter: (cn=*)
        name_attribute: cn
    role:
        base_dn: dc=nyumc,dc=org
    #    filter: (ou=group) #Optional
    #    fitler: (ou=)
        name_attribute: cn
        user_attribute: member
        user_id: username

#  user_class: IMAG\LdapBundle\User\LdapUser # Optional
        

