<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HcpcsCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HcpcsCodeRepository extends EntityRepository
{
    public function searchHcpcs( $name ){
        $qb = $this->createQueryBuilder('c');
        //$qb->where( 'c.name LIKE :name' )
        //    ->setParameter( 'name', '%'. $name .'%' );

        return $qb->getQuery()->getResult();
    }
}
